// Code generated by MockGen. DO NOT EDIT.
// Source: ./store/store.go

// Package mock_store is a generated GoMock package.
package mocks

import (
	big "math/big"
	reflect "reflect"

	model "github.com/catalogfi/ob/model"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockServerStore is a mock of Store interface.
type MockServerStore struct {
	ctrl     *gomock.Controller
	recorder *MockServerStoreMockRecorder
}

// MockServerStoreMockRecorder is the mock recorder for MockServerStore.
type MockServerStoreMockRecorder struct {
	mock *MockServerStore
}

// NewMockServerStore creates a new mock instance.
func NewMockServerStore(ctrl *gomock.Controller) *MockServerStore {
	mock := &MockServerStore{ctrl: ctrl}
	mock.recorder = &MockServerStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerStore) EXPECT() *MockServerStoreMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockServerStore) CancelOrder(creator string, orderID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", creator, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockServerStoreMockRecorder) CancelOrder(creator, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockServerStore)(nil).CancelOrder), creator, orderID)
}

// CreateOrder mocks base method.
func (m *MockServerStore) CreateOrder(creator, sendAddress, receiveAddress, orderPair, sendAmount, receiveAmount, secretHash, userWalletBTCAddress string, config model.Config) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", creator, sendAddress, receiveAddress, orderPair, sendAmount, receiveAmount, secretHash, userWalletBTCAddress, config)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockServerStoreMockRecorder) CreateOrder(creator, sendAddress, receiveAddress, orderPair, sendAmount, receiveAmount, secretHash, userWalletBTCAddress, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockServerStore)(nil).CreateOrder), creator, sendAddress, receiveAddress, orderPair, sendAmount, receiveAmount, secretHash, userWalletBTCAddress, config)
}

// FillOrder mocks base method.
func (m *MockServerStore) FillOrder(orderID uint, filler, sendAddress, receiveAddress string, config model.Network) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillOrder", orderID, filler, sendAddress, receiveAddress, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// FillOrder indicates an expected call of FillOrder.
func (mr *MockServerStoreMockRecorder) FillOrder(orderID, filler, sendAddress, receiveAddress, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillOrder", reflect.TypeOf((*MockServerStore)(nil).FillOrder), orderID, filler, sendAddress, receiveAddress, config)
}

// FilterOrders mocks base method.
func (m *MockServerStore) FilterOrders(maker, taker, orderPair, secretHash, sort string, status model.Status, minPrice, maxPrice, minAmount, maxAmount float64, page, perPage int, verbose bool) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterOrders", maker, taker, orderPair, secretHash, sort, status, minPrice, maxPrice, minAmount, maxAmount, page, perPage, verbose)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterOrders indicates an expected call of FilterOrders.
func (mr *MockServerStoreMockRecorder) FilterOrders(maker, taker, orderPair, secretHash, sort, status, minPrice, maxPrice, minAmount, maxAmount, page, perPage, verbose interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterOrders", reflect.TypeOf((*MockServerStore)(nil).FilterOrders), maker, taker, orderPair, secretHash, sort, status, minPrice, maxPrice, minAmount, maxAmount, page, perPage, verbose)
}

// GetActiveOrders mocks base method.
func (m *MockServerStore) GetActiveOrders() ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveOrders")
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveOrders indicates an expected call of GetActiveOrders.
func (mr *MockServerStoreMockRecorder) GetActiveOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveOrders", reflect.TypeOf((*MockServerStore)(nil).GetActiveOrders))
}

// GetActiveSwaps mocks base method.
func (m *MockServerStore) GetActiveSwaps(chain model.Chain) ([]model.AtomicSwap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSwaps", chain)
	ret0, _ := ret[0].([]model.AtomicSwap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSwaps indicates an expected call of GetActiveSwaps.
func (mr *MockServerStoreMockRecorder) GetActiveSwaps(chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSwaps", reflect.TypeOf((*MockServerStore)(nil).GetActiveSwaps), chain)
}

// GetOrder mocks base method.
func (m *MockServerStore) GetOrder(orderID uint) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", orderID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockServerStoreMockRecorder) GetOrder(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockServerStore)(nil).GetOrder), orderID)
}

// GetOrderBySwapID mocks base method.
func (m *MockServerStore) GetOrderBySwapID(swapID uint) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderBySwapID", swapID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderBySwapID indicates an expected call of GetOrderBySwapID.
func (mr *MockServerStoreMockRecorder) GetOrderBySwapID(swapID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderBySwapID", reflect.TypeOf((*MockServerStore)(nil).GetOrderBySwapID), swapID)
}

// GetOrdersByAddress mocks base method.
func (m *MockServerStore) GetOrdersByAddress(address string) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByAddress", address)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByAddress indicates an expected call of GetOrdersByAddress.
func (mr *MockServerStoreMockRecorder) GetOrdersByAddress(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByAddress", reflect.TypeOf((*MockServerStore)(nil).GetOrdersByAddress), address)
}

// Gorm mocks base method.
func (m *MockServerStore) Gorm() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gorm")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// Gorm indicates an expected call of Gorm.
func (mr *MockServerStoreMockRecorder) Gorm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gorm", reflect.TypeOf((*MockServerStore)(nil).Gorm))
}

// SwapByOCID mocks base method.
func (m *MockServerStore) SwapByOCID(ocID string) (model.AtomicSwap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwapByOCID", ocID)
	ret0, _ := ret[0].(model.AtomicSwap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SwapByOCID indicates an expected call of SwapByOCID.
func (mr *MockServerStoreMockRecorder) SwapByOCID(ocID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwapByOCID", reflect.TypeOf((*MockServerStore)(nil).SwapByOCID), ocID)
}

// UpdateOrder mocks base method.
func (m *MockServerStore) UpdateOrder(order *model.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", order)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockServerStoreMockRecorder) UpdateOrder(order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockServerStore)(nil).UpdateOrder), order)
}

// UpdateSwap mocks base method.
func (m *MockServerStore) UpdateSwap(swap *model.AtomicSwap) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSwap", swap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSwap indicates an expected call of UpdateSwap.
func (mr *MockServerStoreMockRecorder) UpdateSwap(swap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSwap", reflect.TypeOf((*MockServerStore)(nil).UpdateSwap), swap)
}

// ValueLockedByChain mocks base method.
func (m *MockServerStore) ValueLockedByChain(chain model.Chain, config model.Network) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValueLockedByChain", chain, config)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValueLockedByChain indicates an expected call of ValueLockedByChain.
func (mr *MockServerStoreMockRecorder) ValueLockedByChain(chain, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValueLockedByChain", reflect.TypeOf((*MockServerStore)(nil).ValueLockedByChain), chain, config)
}
