name: Docker Builder

on:
  push:
    tags:
      - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Extract tag
              id: version_tag
              run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACCESS_TOKEN }}

            - name: Build and push Docker images
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  build-args: PAT=${{ secrets.ACCESS_TOKEN }}
                  push: true
                  tags: |
                      ghcr.io${{ github.organisation }}/${{ github.repository }}:latest
                      ghcr.io${{ github.organisation }}/${{ github.repository }}:${{ steps.version_tag.outputs.tag }}